---
- name: Deploy Inventory App
  hosts: localhost
  become: yes
  tasks:
    - name: Stop and remove existing container
      docker_container:
        name: inventory-app
        state: absent
      ignore_errors: yes

    - name: Pull latest image
      docker_image:
        name: "admin/inventory-app:latest"
        source: pull
        force_source: yes

    - name: Run the container
      docker_container:
        name: inventory-app
        image: "admin/inventory-app:latest"
        state: started
        restart_policy: always
        ports:
          - "8089:8080"
