---
- name: Deploy BankPro Inventory App
  hosts: aws_server
  become: yes
  tasks:
    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull latest Docker image
      docker_image:
        name: "your-dockerhub-username/inventory-app:latest"
        source: pull

    - name: Stop existing container
      docker_container:
        name: inventory-app
        state: absent

    - name: Run new container
      docker_container:
        name: inventory-app
        image: "your-dockerhub-username/inventory-app:latest"
        state: started
        ports:
          - "8089:8080" # Maps AWS port 8089 to App port 8080
